#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - apache2
  - apache2-utils
  - curl
  - software-properties-common
  - unattended-upgrades
runcmd:
  - add-apt-repository ppa:ondrej/php
  - apt install php7.4
  - apt install php7.4-common php7.4-mysql php7.4-xml php7.4-xmlrpc php7.4-curl php7.4-gd php7.4-imagick php7.4-cli php7.4-dev php7.4-imap php7.4-mbstring php7.4-opcache php7.4-soap php7.4-zip php7.4-intl -y
  - a2enmod php7.4